package net.galaxycore.citybuild.pmenu.menu.flags;

public enum FlagHolder {
    ENTITY_CAP           ("", "", "", ""),
    EXPLOSION            ("", "", "", ""),
    MUSIC                ("", "", "", ""),
    FLIGHT               ("", "", "", ""),
    UNTRUSTED            ("", "", "", ""),
    DENY_EXIT            ("", "", "", ""),
    CHAT                 ("", "", "", ""),
    DESCRIPTION          ("", "", "", ""),
    GREETING             ("", "", "", ""),
    FAREWELL             ("", "", "", ""),
    WEATHER              ("", "", "", ""),
    ANIMAL_ATTACK        ("", "", "", ""),
    ANIMAL_CAP           ("", "", "", ""),
    ANIMAL_INTERACT      ("", "", "", ""),
    BLOCK_BURN           ("", "", "", ""),
    BLOCK_IGNITION       ("", "", "", ""),
    BREAK                ("", "", "", ""),
    DEVICE_INTERACT      ("", "", "", ""),
    DISABLE_PHYSICS      ("", "", "", ""),
    DROP_PROTECTION      ("", "", "", ""),
    FEED                 ("", "", "", ""),
    FORCEFIELD           ("", "", "", ""),
    GRASS_GROW           ("", "", "", ""),
    HANGING_BREAK        ("", "", "", ""),
    HANGING_PLACE        ("", "", "", ""),
    HEAL                 ("", "", "", ""),
    HIDE_INFO            ("", "", "", ""),
    HOSTILE_ATTACK       ("", "", "", ""),
    HOSTILE_CAP          ("", "", "", ""),
    HOSTILE_INTERACT     ("", "", "", ""),
    ICE_FORM             ("", "", "", ""),
    ICE_MELT             ("", "", "", ""),
    INSTABREAK           ("", "", "", ""),
    INVINCIBLE           ("", "", "", ""),
    ITEM_DROP            ("", "", "", ""),
    KELP_GROW            ("", "", "", ""),
    LIQUID_FLOW          ("", "", "", ""),
    MISC_BREAK           ("", "", "", ""),
    MISC_CAP             ("", "", "", ""),
    MISC_INTERACT        ("", "", "", ""),
    MISC_PLACE           ("", "", "", ""),
    MOB_BREAK            ("", "", "", ""),
    MOB_CAP              ("", "", "", ""),
    MOB_PLACE            ("", "", "", ""),
    ENTITY_CHANGE_BLOCK  ("", "", "", ""),
    MYCEL_GROW           ("", "", "", ""),
    NOTIFY_ENTER         ("", "", "", ""),
    NOTIFY_LEAVE         ("", "", "", ""),
    NO_WORLDEDIT         ("", "", "", ""),
    PLACE                ("", "", "", ""),
    PLAYER_INTERACT      ("", "", "", ""),
    PRICE                ("", "", "", ""),
    PVE                  ("", "", "", ""),
    PVP                  ("", "", "", ""),
    REDSTONE             ("", "", "", ""),
    SERVER_PLOT          ("", "", "", ""),
    SNOW_FORM            ("", "", "", ""),
    COPPER_OXIDE         ("", "", "", ""),
    SNOW_MELT            ("", "", "", ""),
    SOIL_DRY             ("", "", "", ""),
    CORAL_DRY            ("", "", "", ""),
    CROP_GROW            ("", "", "", ""),
    TAMED_ATTACK         ("", "", "", ""),
    TAMED_INTERACT       ("", "", "", ""),
    TIME                 ("", "", "", ""),
    TITLES               ("", "", "", ""),
    TITLE                ("", "", "", ""),
    USE                  ("", "", "", ""),
    VEHICLE_BREAK        ("", "", "", ""),
    VEHICLE_CAP          ("", "", "", ""),
    VEHICLE_PLACE        ("", "", "", ""),
    VEHICLE_USE          ("", "", "", ""),
    VILLAGER_INTERACT    ("", "", "", ""),
    VINE_GROW            ("", "", "", ""),
    DENY_TELEPORT        ("", "", "", ""),
    GAMEMODE             ("", "", "", ""),
    GUEST_GAMEMODE       ("", "", "", ""),
    BLOCKED_CMDS         ("", "", "", ""),
    KEEP                 ("", "", "", ""),
    KEEP_INVENTORY       ("", "", "", ""),
    DENY_PORTAL_TRAVEL   ("", "", "", ""),
    DENY_PORTALS         ("", "", "", ""),
    LECTERN_READ_BOOK    ("", "", "", ""),
    PREVENT_CREATIVE_COPY("", "", "", ""),
    LEAF_DECAY           ("", "", "", "");

    private final String nameGer;
    private final String nameEn;
    private final String descGer;

    FlagHolder(String nameGer, String nameEn, String descGer, String descEn) {

        this.nameGer = nameGer;
        this.nameEn = nameEn;
        this.descGer = descGer;
    }
}
