kind: pipeline
name: Citybuild-Master
type: docker

steps:
  - name: test'n'deploy
    image: maven:3-jdk-16
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn test -B -s workflow_settings.xml
      - mvn deploy -B -s workflow_settings.xml

trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
name: Citybuild
type: docker

steps:
  - name: test
      image: maven:3-jdk-16
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn test -B -s workflow_settings.xml

trigger:
  event:
    - push