kind: pipeline
name: Citybuild-Master
type: docker

steps:
  - name: test'n'deploy
    image: maven:3.8.5-eclipse-temurin-17
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn test -B -s workflow_settings.xml
      - mvn deploy -B -s workflow_settings.xml

trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
name: Citybuild
type: docker

steps:
  - name: test
    image: maven:3.8.5-eclipse-temurin-17
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn test -B -s workflow_settings.xml

trigger:
  event:
    - push
---
kind: pipeline
name: Citybuild-Reports
type: docker
steps:
  - name: report
    image: jetbrains/qodana-jvm-community:2021.3
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - cp workflow_settings.xml ~/.m2/settings.xml
      - qodana
