name: Essential
version: '${project.version}'
main: net.galaxycore.citybuild.Essential
api-version: 1.16
author: TheNick24
description: CityBuild Plugin für GalaxyCore.net
depend:
  - GalaxyCoreCore
commands:
  Debug:
    description: Gibt dir eine Test Nachricht aus.
  Gamemode:
    description: Setzt dich in verschiedene Spielmodi.
    aliases: [ "gm" ]
  Heal:
    description: Füllt dein Hunger und deine Herzen wieder auf.
  Fly:
    description: Setzt dich oder andere Spieler in den Flugmodus
  Feed:
    description: DU kannst deine oder andere Hungerleisten auffüllen
  Workbench:
    description: Öffnet eine Mobile Werkbank
    aliases: [ "wb", "craft" ]
  Anvil:
    description: Öffnet einen Mobilen Amboss
    aliases: [ "av" ]
  Day:
    description: Ändert die TagesZeit auf Tag
    aliases: [ "d" ]
  Night:
    description: Ändert die TagesZeit auf Nacht
    aliases: [ "n" ]
  Hat:
    description: Setzt dir das Item in deiner Hand auf deinen Kopf
  Weather:
    description: Ändert das Weather in 3 verschieden Möglichkeiten
  God:
    description: Setzt dich in einen unverwundbaren Modus
  Teleport:
    description: Teleportiert dich zu anderen Spielern
    aliases: [ "tp" ]
  Spawn:
    description: Teleportiert dich zum Spawn

