name: Essential
version: '${project.version}'
main: net.galaxycore.citybuild.Essential
api-version: 1.16
author: TheNick24
description: CityBuild Plugin für GalaxyCore.net
depend:
  - GalaxyCoreCore
commands:
  Debug:
    description:

  Gamemode:
    description:
    aliases: [ "gm" ]
  Heal:
    description: Füllt dein Hunger und deine Herzen wieder auf.
  Fly:
    description:
  Feed:
    description:
  Workbench:
    description:
    aliases: [ "wb", "craft" ]
  Anvil:
    description:
    aliases: [ "av" ]
  Day:
    description:
    aliases: [ "d" ]
  Night:
    description:
    aliases: [ "n" ]
  Hat:
    description:
  Weather:
    description:
  God:
    description:

