name: Essential
version: '${project.version}'
main: net.galaxycore.citybuild.Essential
api-version: 1.16
author: TheNick24
description: CityBuild Plugin für GalaxyCore.net
depend:
  - GalaxyCoreCore
commands:
  Debug:
  Gamemode:
    aliases: [ "gm" ]
  Heal:
    description: Füllt dein Hunger und deine Herzen wieder auf.
  Fly:

  Feed:

  Workbench:
    aliases: [ "wb" ]

  Anvil:
    aliases: [ "av" ]